/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IDRCVaultContract extends Truffle.Contract<IDRCVaultInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IDRCVaultInstance>;
}

export interface Deposit {
  name: "Deposit";
  args: {
    user: string;
    amount: BN;
    0: string;
    1: BN;
  };
}

export interface Withdraw {
  name: "Withdraw";
  args: {
    user: string;
    amount: BN;
    0: string;
    1: BN;
  };
}

type AllEvents = Deposit | Withdraw;

export interface IDRCVaultInstance extends Truffle.ContractInstance {
  /**
   * Name of the contract
   */
  name(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * DRC Address
   */
  drcAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * Total DRC Amount locked
   */
  totalAmountLocked(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * DRC balance of an account in the Vault
   * @param account Address of an account
   */
  balanceOf(
    account: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * DRC Vault holder list
   */
  holders(txDetails?: Truffle.TransactionDetails): Promise<string[]>;

  /**
   * Deposit DRC to the Vault
   * @param account Address to deposit to
   * @param amount Amount of DRC to deposit
   */
  deposit: {
    (
      account: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      account: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      account: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      account: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Withdraw DRC from the Vault
   * @param amount Amount of DRC to withdraw
   */
  withdraw: {
    (
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    /**
     * Name of the contract
     */
    name(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * DRC Address
     */
    drcAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * Total DRC Amount locked
     */
    totalAmountLocked(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * DRC balance of an account in the Vault
     * @param account Address of an account
     */
    balanceOf(
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * DRC Vault holder list
     */
    holders(txDetails?: Truffle.TransactionDetails): Promise<string[]>;

    /**
     * Deposit DRC to the Vault
     * @param account Address to deposit to
     * @param amount Amount of DRC to deposit
     */
    deposit: {
      (
        account: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        account: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        account: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        account: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Withdraw DRC from the Vault
     * @param amount Amount of DRC to withdraw
     */
    withdraw: {
      (
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
