/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { DRCVaultContract } from "./DRCVault";
import { IDRCVaultContract } from "./IDRCVault";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "DRCVault"): DRCVaultContract;
      require(name: "IDRCVault"): IDRCVaultContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export { DRCVaultContract, DRCVaultInstance } from "./DRCVault";
export { IDRCVaultContract, IDRCVaultInstance } from "./IDRCVault";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
